<?=$this->doctype ();?>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
<head>
	<meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
	<title>Zeus - Accueil</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= $this->headLink()->prependStylesheet('/css/bootstrap-theme.min.css'); ?>
    <?= $this->headLink()->prependStylesheet('/css/bootstrap.min.css'); ?>
    <?= $this->headLink()->prependStylesheet('/css/jquery-ui-1.10.4.min.css'); ?>
    <style>
		body{
			font-size:100%;
		}
		header .col-md-2{height:80px; background:yellow}
		header .col-md-6{height:80px; background:grey}
		header .col-md-4{height:80px; background:pink}
		
		header .col-md-7{height:20px; background:blue}
		header .col-md-5{height:20px; background:brown}
		
		
		
	</style>
</head>
<body>
	<div class="container">
		<header class="row">
			<div class="row">
				<div class="col-md-2">Logo</div>
				<div class="col-md-6">Phrase administrable</div>
				<div class="col-md-4">espace connexion</div>
			</div>
			
			<div class="row">
				<div class="col-md-7">Onglets thèmes administrables</div>
				<div class="col-md-5">Barre de recherche rapide</div>
			</div>
			
		</header>
		<div class="row">
			<aside class="col-md-2">Col gauche</aside>
			<article class="col-md-8"><?=$this->layout ()->content;?></article>
			<aside class="col-md-2">Col droite</aside>
		</div>
		<footer class="row">
			<div class="col-md-3">Plan du site</div>
			<div class="col-md-3">Motes clés</div>
			<div class="col-md-3">espace téléchargement</div>
			<div class="col-md-3">Liens utles</div>
		</footer>	
	</div>
	<?php
		echo $this->headScript ()->prependFile ( '/js/jquery-1.11.0.min.js' );
		echo $this->headScript ()->prependFile ( '/js/bootstrap.min.js' );
		echo $this->headScript ()->prependFile ( '/js/jquery-ui-1.10.4.min.js' );
		echo $this->headScript ()->prependFile ( '/js/plugins.js' );
		echo $this->headScript ()->prependFile ( '/js/main.js' );
		echo $this->headScript ()->prependFile ( '/js/jquery.fittext.js' );
	?>
</body>