<?=$this->doctype ();?>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
<head>
	<meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
	<title>Zeus - Accueil</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= $this->headLink()->prependStylesheet('/css/bootstrap-theme.min.css'); ?>
    <?= $this->headLink()->prependStylesheet('/css/bootstrap.min.css'); ?>
    <?= $this->headLink()->prependStylesheet('/css/jquery-ui-1.10.4.min.css'); ?>
    
</head>
<body>
	<div class="container">
		<header>Header</header>
		<section class="row">
			<?=$this->layout ()->content;?>
		</section>
		<footer>Footer</footer>	
	</div>
	<?php
		echo $this->headScript ()->prependFile ( '/js/bootstrap.min.js' );
		echo $this->headScript ()->prependFile ( '/js/jquery-1.11.0.min.js' );
		echo $this->headScript ()->prependFile ( '/js/jquery-ui-1.10.4.min.js' );
		echo $this->headScript ()->prependFile ( '/js/plugins.js' );
		echo $this->headScript ()->prependFile ( '/js/main.js' );
	?>
</body>